import FWCore.ParameterSet.Config as cms

input_files = cms.untracked.vstring()
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.0_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.10_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.11_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.12_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.13_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.14_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.15_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.16_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.17_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.18_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.19_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.1_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.2_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.3_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.4_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.5_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.6_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.7_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.8_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10327.9_re_reco.root")

# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.0_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.1_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.2_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.3_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.4_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.5_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.6_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.7_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.8_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10328.9_re_reco.root")

# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.0_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.1_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.2_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.3_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.4_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.5_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.7_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.8_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10329.9_re_reco.root")

input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.0_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.10_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.11_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.12_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.13_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.14_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.15_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.16_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.17_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.18_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.19_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.1_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.20_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.21_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.22_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.23_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.24_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.25_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.26_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.27_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.28_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.29_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.2_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.30_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.31_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.32_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.33_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.34_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.35_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.36_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.37_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.3_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.4_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.5_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.6_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.7_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.8_re_reco.root")
input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10331.9_re_reco.root")

# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.0_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.10_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.11_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.12_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.13_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.14_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.15_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.16_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.17_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.1_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.2_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.3_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.4_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.5_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.6_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.7_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.8_re_reco.root")
# input_files.append("root://eostotem.cern.ch//eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version3/run_10332.9_re_reco.root")